backend:
  name: github
  repo: gitbreaker222/metalify-riot-starter #user/repo
  branch: master

media_folder: "src/media"
public_folder: "/media"
publish_mode: editorial_workflow

collections:
  - name: "index"
    label: "Frontpage"
    folder: "src/content"
    create: false
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "layout"}
      - {label: "Title", name: "title", widget: "string"}
      -
        label: "Exclude from menu?"
        name: "hideInMenu"
        widget: "boolean"
        default: false
        required: false
      -
        label: "Index in menu (empty or 0 for auto order)"
        name: "menuIndex"
        widget: "number"
        default: 0
        required: false
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Posts" # Used in the UI
    folder: "src/content/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: {{slug}}
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      -
        label: "Exclude from menu?"
        name: "hideInMenu"
        widget: "boolean"
        default: false
        required: false
      -
        label: "Index in menu (empty or 0 for auto order)"
        name: "menuIndex"
        widget: "number"
        default: 0
        required: false
      - {label: "Publish Date", name: "date", widget: "datetime"} # TODO default today
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "settings" # Used in routes, e.g., /admin/collections/blog
    label: "Settings" # Used in the UI
    folder: "src/content/settings" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: {{slug}}
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "layout"} #TODO change to setting
      - {label: "Title", name: "title", widget: "string", pattern: [".{10,}", "Should have more than 10 characters"] }
      - {label: "Description", name: "description", widget: "text", required: false}
      - label: "Exclude from menu?"
        name: "hideInMenu"
        widget: "boolean"
        default: false
        required: false
      - label: "Index in menu (empty or 0 for auto order)"
        name: "menuIndex"
        widget: "number"
        default: 0
        required: false
      - {label: "Publish Date", name: "date", widget: "datetime", required: false}
      - {label: "Number", name: "number", widget: "number", required: false}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "File", name: "file", widget: "file", required: false}
      - label: Object
        name: object
        widget: object
        fields:
          - {label: Title, name: title, widget: string, tagname: h1}
          - {label: Published, name: published, widget: boolean}
          - {label: Loud, name: loud, widget: boolean}
          - {label: Message, name: message, widget: text}
          - {label: URL, name: url}
        required: false
      - label: "List"
        name: "list"
        widget: "list"
        required: false
        fields:
          - {label: Title, name: title, widget: string, tagname: h1}
          - {label: Published, name: published, widget: boolean}
          - {label: Loud, name: loud, widget: boolean}
          - {label: Message, name: message, widget: text}
          - {label: URL, name: url}
      - label: Relation (posts name)
        name: relation
        widget: relation
        collection: posts
        searchFields: [title]
        valueField: title
        required: false
      #- {label: "Body", name: "body", widget: "markdown"}

  - name: "timetable"
    label: "Opening times"
    folder: "src/content/settings"
    create: true
    slug: {{slug}}
    fields:
      - label: "Monday"
        name: "time1"
        widget: "list"
        required: false
        fields:
          - {label: From (hour), name: time1_from_h, widget: number}
          - {label: From (minute), name: time1_from_m, widget: number}
          - {label: To (hour), name: time1_to_h, widget: number}
          - {label: To (minute), name: time1_to_m, widget: number}
