backend:
  name: github
  repo: gitbreaker222/metalify-riot-starter #user/repo
  branch: master

media_folder: "src/media"
public_folder: "/media"
publish_mode: editorial_workflow

collections:
  - name: "index"
    label: "Frontpage"
    folder: "src/content"
    create: false
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "layout"}
      - {label: "Title", name: "title", widget: "string"}
      -
        label: "Exclude from menu?"
        name: "hideInMenu"
        widget: "boolean"
        default: false
        required: false
      -
        label: "Index in menu (empty or 0 for auto order)"
        name: "menuIndex"
        widget: "number"
        default: 0
        required: false
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Posts" # Used in the UI
    folder: "src/content/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: {{slug}}
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      -
        label: "Exclude from menu?"
        name: "hideInMenu"
        widget: "boolean"
        default: false
        required: false
      -
        label: "Index in menu (empty or 0 for auto order)"
        name: "menuIndex"
        widget: "number"
        default: 0
        required: false
      - {label: "Publish Date", name: "date", widget: "datetime"} #default today
      - {label: "Featured Image", name: "thumbnail", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
